version: 0.2
env:
  variables:
    GOTESTSUM_JUNITFILE: 'functional-tests.xml'
    GOTESTSUM_FORMAT: 'standard-verbose'
  parameter-store:
    TF_VAR_target: '/NewParam/secure1'
phases:
  install:
    runtime-versions:
       golang: latest
       python: 3.7
    commands:
      - python --version
      - go version
      - echo $TF_VAR_target
