# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - echo "WOW"
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install unit.js
      - cat /etc/shells
      - export SHELL="/bin/bash"
      - echo $SHELL
      - export SERVER_KEY="a b c"
      - set -a
      - cat /codebuild/output/tmp/script.sh
      - echo $SERVER_KEY | tr [:space:] "\n"
      - cat /codebuild/output/tmp/dir.txt
      - cat /codebuild/output/tmp/env.sh 
      - echo ${SERVER_KEY// /'\n'}
      - echo $WOW
      - echo $WOW
      - echo $NICE
      
     
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - mocha test.js
      - echo $WOW
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $WOW
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*
